<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Program.fs"/>
        <Compile Include="Intro2.fs" />
        <Compile Include="Exercise1dot4.cs" />
        <Compile Include="Intcomp1.fs" />
    </ItemGroup>

</Project>
